### ISSUE TITLE
Enviroment file

### ISSUE THREAD

**Issue by oyvindhagen2** [farizrahman4u/loopgpt#16] opened 2023-04-23 18:38 UTC
Hi, Could you include and inviroment file that can be edited directly?

**Comment by maker57sk** [comment] 2023-04-26 08:39
Inside loopgpt dir rename [.env.template] to [.env] and change the  "REPLACE-THIS-WITH-YOUR-API-KEY" with your open ai api key

**Comment by devsktlabs** [comment] 2023-04-27 13:48
even after adding .env file with open_api_key I receive environment variable error. api key not found. i've placed it in root directory as well as /loopgpt directory and still the same error.  Anyone else running into this?

**Comment by tylerlindell** [comment] 2023-04-27 17:22
> even after adding .env file with open_api_key I receive environment variable error. api key not found. i've placed it in root directory as well as /loopgpt directory and still the same error. Anyone else running into this?

OPENAI_API_KEY should be all caps. it seems to work for me.

**Comment by FayazRahman** [comment] 2023-04-28 09:34
> even after adding .env file with open_api_key I receive environment variable error. api key not found. i've placed it in root directory as well as /loopgpt directory and still the same error. Anyone else running into this?

Hey @devsktlabs, can you tell me if you are using windows?

**Comment by tylerlindell** [comment] 2023-04-28 13:10
> > even after adding .env file with open_api_key I receive environment variable error. api key not found. i've placed it in root directory as well as /loopgpt directory and still the same error. Anyone else running into this?
> 
> Hey @devsktlabs, can you tell me if you are using windows?

I recognize you are addressing @devsktlabs directly but to clarify on my end, I am on Windows 10 and it is working for me.

**Comment by tylerlindell** [comment] 2023-04-28 13:15
@devsktlabs can you copy/paste you `.env` here? Please hide any sensitive data.

more detail would be good on the commands your running, which cli you're using, etc. give us the ability to reproduce :-)

**Comment by devsktlabs** [comment] 2023-04-28 13:16
I've tried like this 
`OPENAI_API_KEY = "sk-mykey`

also like this 
`OPENAI_API_KEY=sk-mykey`

**Comment by devsktlabs** [comment] 2023-04-28 13:17
Using autogpt daily and no issues on that one btw

**Comment by tylerlindell** [comment] 2023-04-28 13:19
same here but I'm not facing issues on either repo :-)

what does the CLI output or error look like? screenshot or something?

**Comment by devsktlabs** [comment] 2023-04-28 13:20
<img width="753" alt="image" src="https://user-images.githubusercontent.com/127240935/235158649-151dcd3a-30f2-407f-8c3f-cab9d2f42d81.png">

**Comment by tylerlindell** [comment] 2023-04-28 13:22
which directory is the .env file? is the name of the .env file exactly that without whitespace?

**Comment by FayazRahman** [comment] 2023-04-28 13:22
@tylerlindell Thanks for confirming its working on your end.
@devsktlabs Have you enabled "show file extension" on windows? The env file in our repo is `.env.template`, so if the "show file extension" is not enabled, the `.template` will be hidden. If this is the case, you need to change it so that the file name is just `.env`

**Comment by devsktlabs** [comment] 2023-04-28 13:23
<img width="197" alt="image" src="https://user-images.githubusercontent.com/127240935/235159145-791c49ec-4dfa-458a-bb31-880413696f7b.png">

maybe its possible docker is messing it up. I can try to pull fresh

**Comment by tylerlindell** [comment] 2023-04-28 13:24
I'm using it w/o docker

**Comment by devsktlabs** [comment] 2023-04-28 13:27
Same outcome with a fresh clone... hmm at a loss on this one

**Comment by tylerlindell** [comment] 2023-04-28 13:29
what directory are you within while trying to run your python command?

**Comment by devsktlabs** [comment] 2023-04-28 13:30
the fresh clone is in /looptest, .env is in /looptest and I am running "loopgpt run" in the same directory.

**Comment by devsktlabs** [comment] 2023-04-28 13:32
<img width="721" alt="image" src="https://user-images.githubusercontent.com/127240935/235161412-67b5b0b1-0238-4848-866e-6f8221fd1beb.png">

**Comment by tylerlindell** [comment] 2023-04-28 13:37
try ```python ./examples/research_gpt.py```

**Comment by devsktlabs** [comment] 2023-04-28 13:39
`PS C:\looptest> python ./examples/research_gpt.py 
WARNING: OpenAI API Key not found. Please set the `OPENAI_API_KEY` environment variable. LoopGPT cannot work without it. See https://github.com/farizrahman4u/loopgpt#-requirements for more details

+------------------------------------------------------------+
| ██╗░░░░░░█████╗░░█████╗░██████╗░░██████╗░██████╗░████████╗ |
| ██║░░░░░██╔══██╗██╔══██╗██╔══██╗██╔════╝░██╔══██╗╚══██╔══╝ |
| ██║░░░░░██║░░░░██░░░░██║██████╔╝██║░░██╗░██████╔╝░░░██║░░░ |
| ██║░░░░░██║░░██║██║░░██║██╔═══╝░██║░░╚██╗██╔═══╝░░░░██║░░░ |
| ███████╗╚█████╔╝╚█████╔╝██║░░░░░╚██████╔╝██║░░░░░░░░██║░░░ |
| ╚══════╝░╚════╝░░╚════╝░╚═╝░░░░░░╚═════╝░╚═╝░░░░░░░░╚═╝░░░ |
+------------------------------------------------------------+

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "C:\looptest\examples\research_gpt.py", line 16, in <module>
    agent.cli()
  File "C:\Users\tumol\AppData\Local\Programs\Python\Python311\Lib\site-packages\loopgpt\agent.py", line 471, in cli
    cli(self, continuous=continuous)
  File "C:\Users\tumol\AppData\Local\Programs\Python\Python311\Lib\site-packages\loopgpt\loops\repl.py", line 114, in cli
    resp = agent.chat()
           ^^^^^^^^^^^^
  File "C:\Users\tumol\AppData\Local\Programs\Python\Python311\Lib\site-packages\loopgpt\utils\spinner.py", line 137, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tumol\AppData\Local\Programs\Python\Python311\Lib\site-packages\loopgpt\agent.py", line 173, in chat
    resp = self.model.chat(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\tumol\AppData\Local\Programs\Python\Python311\Lib\site-packages\loopgpt\models\openai_.py", line 32, in chat
    api_key = _getkey(self.api_key)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tumol\AppData\Local\Programs\Python\Python311\Lib\site-packages\loopgpt\models\openai_.py", line 12, in _getkey
    raise ValueError(
ValueError: OpenAI API Key not found. Please set the `OPENAI_API_KEY` environment variable. See https://github.com/farizrahman4u/loopgpt#-requirements for more details`

**Comment by devsktlabs** [comment] 2023-04-28 13:39
is there supposed to be a specific path in my environment variables on windows that i'm missing?

**Comment by tylerlindell** [comment] 2023-04-28 13:43
naw, python and the .env should be able to handle that for you

**Comment by devsktlabs** [comment] 2023-04-28 13:49
its so strange that autogpt find .env in that directory but cannot with loop

**Comment by FayazRahman** [comment] 2023-04-28 13:57
@devsktlabs From your directory, can you open up python and run the following commands:
```python
from dotenv import load_dotenv
import os
load_dotenv()
os.getenv("OPENAI_API_KEY")
```
Does that give you your api key?

**Comment by devsktlabs** [comment] 2023-04-28 14:03
yes that passes the key

**Comment by FayazRahman** [comment] 2023-04-28 14:13
@devsktlabs That makes it even worse because this is the same code we use in the repo 😨 Let me do all the steps just like you did and get back to you. In the meantime, you can set your environment variable `OPENAI_API_KEY` to your key and that will definitely work. See how to set environment variables on windows here: https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/

**Comment by tylerlindell** [comment] 2023-04-28 14:22
> yes that passes the key

looks like you're using vscode! you could try a breakpoint in the code you have there and inspect for more details.

also, I'm not as familiar with powershell - do you have git bash as a terminal option for vscode?

**Comment by FayazRahman** [comment] 2023-04-28 14:26
@devsktlabs I tried the exact same steps and it worked:
```bash
git clone https://github.com/farizrahman4u/loopgpt.git looptest
cd looptest
pip install -e .
```
rename .env.template -> .env
replace api-key

```bash
loopgpt run
```

**Comment by devsktlabs** [comment] 2023-04-28 14:48
ok I removed the entire directory again including .git. started over and went the process @FayazRahman suggested and it is now working. thank you for walking me through this issue. Agents releasing!

**Comment by FayazRahman** [comment] 2023-04-28 15:03
@devsktlabs ♾️🕵️‍♂️

**Comment by tylerlindell** [comment] 2023-04-28 15:31
seems like we might be able to close this now

**Closed** 2023-04-29 07:23 UTC

**Comment by swapneils** [comment] 2023-05-05 04:05
This seems to still be an issue if downloaded via pip? Using git and pip install -e work fine, but pip install loopgpt and putting .env in the directory with my runagent.py can't find the openai key, even though the os.getenv works fine.

I think we might want users to optionally provide the agent with an environment (and propagate that to the tools, of course), so that the pip package can work without having to set environment variables.
